### ISSUE TITLE
Is there a plan to support difference?

### ISSUE THREAD

**Issue by cuixiping** [lys-lang/node-ebnf#24]
**Error: Difference not supported yet**

```
ALL_CHARS    ::= [#x20-#xffff]
NON_QUOTE  ::= ALL_CHARS - '"'
```

I know we can split it to two parts. But it's simpler if '-' is supported.

**Comment by menduz** [comment]
You can mock that behavior with a negative look ahead

```ebnf
ALL_CHARS    ::= [#x20-#xffff]
NON_QUOTE  ::= !'"' ALL_CHARS
```

**Comment by cuixiping** [comment]
> You can mock that behavior with a negative look ahead
> 
> ```ebnf
> ALL_CHARS    ::= [#x20-#xffff]
> NON_QUOTE    ::= !'"' ALL_CHARS
> ```

Thank you!
