### ISSUE TITLE
Support writing one rule in mutiple lines

### ISSUE THREAD

**Issue by cuixiping** [lys-lang/node-ebnf#25]
For example:
```
rule
       ::= 'A'
         | 'B'
         | 'C'
```
This syntax should be supported. 
It throw errors now.

**Comment by menduz** [comment]
To write multi line rules you should use parentheses and avoid the newline after the name of the rule

```ebnf
rule   ::= ( 'A'
           | 'B'
           | 'C' )
```

Here is an example https://github.com/lys-lang/node-ebnf/blob/7f6df026be606ff0439979d23039a7d3b0547f2c/test/NewLang.spec.ts#L102-L112

It should work

**Comment by cuixiping** [comment]
OK, thank you!

**Comment by menduz** [comment]
Last time that page was updated was in 2016.. https://github.com/menduz/ebnf-highlighter

**Comment by cuixiping** [comment]
> Last time that page was updated was in 2016.. https://github.com/menduz/ebnf-highlighter

I cloned and built the repo with new version of node-ebnf. It works as expect now.
Thank you!
