### ISSUE TITLE
Incorrect parse errors

### ISSUE THREAD

**Issue by tgrosinger** [lys-lang/node-ebnf#34]
These examples were all tested using https://menduz.com/ebnf-highlighter/ but were also reproduced locally on version 1.9.0. I believe there are also similar issues in the BNF parser.

In the following grammar:

```
value            ::= component | range
range            ::= component ".." component /* broken */
component        ::= row | column | row column /* broken */
row              ::= "@" number
column           ::= "$" number
number           ::= [0-9]+
```

In testing there are some unexpected results.

`@2` is correctly parsed as `value -> component -> row -> number

The `range` directive is not parsing correctly. For example, `@2..@2` should be `value -> range -> (component -> row -> number , component -> row -> number)`

The `row column` aspect of `component` is also not correctly parsed. For example, `@2$2`

**Comment by menduz** [comment]
Hello Tony, keep in mind that the parser generates a PEG parser, therefore it behaves like a deterministic state machine (like regular expressions). **The generated parser pays attention to the order of the constructions, not being able handling ambiguity.**

Try changing the order of the rules, so it first tries to parse the `row column` and then try `row` as a fallback.

```diff
-component        ::= row | column | row column /* broken */
+component        ::= row column | column | row
```

If it doesn't work, write here and I'll try to help.

**Comment by tgrosinger** [comment]
Ah, that fixed it. Thank you!
