### ISSUE TITLE
Cannot be used in a browser with a CSP set that does not include the `unsafe-eval` permission

### ISSUE THREAD

**Issue by snoozbuster** [lys-lang/node-ebnf#48]
The usage of `eval` [in Parser.ts](https://github.com/lys-lang/node-ebnf/blob/master/src/Parser.ts#L276) prevents the library from being used in any browser-based application that disallows eval for security reasons. The error thrown is a generic "Cannot parse (valid grammar)" error, which may be the origin of the issue in #43.

**Comment by menduz** [comment]
Can you pin point the file including eval? From what I recall, this lib should not include it anywhere

**Comment by snoozbuster** [comment]
I included a link to the offending line in my OP. Parser.ts, line 276. There is a tslint-ignore comment directly above it to allow the use of it. It seems to be used exclusively to turn a JSON string into a JS string - for which JSON.parse would also work.

**Comment by menduz** [comment]
If that's the case, it should certainly work. Will try from the github UI hoping the CI is still working.

I didn't see the link from mobile, my bad

**Comment by menduz** [comment]
Would you test if `ebnf@1.9.1-20230608193331.commit-82e9a84` solves the issue?

**Comment by snoozbuster** [comment]
I can't really... I was consuming this package as a part of [json-schema-library](https://github.com/sagold/json-schema-library), which itself uses this package as part of [json-query](https://github.com/sagold/json-query). But if the eval is gone that will definitely solve the underlying problem

**Comment by menduz** [comment]
Ok, will publish a patch. Tests are passing and are extensive

**Comment by snoozbuster** [comment]
Thanks! I'll see if I can get the downstream library I was trying to use to pick up the update.
